name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag renti_frontend:v1

    - name: Run a docker container from the image
      run: docker run --name Renti -d -p 3000:3000 renti_frontend:v1

    - name: Wait for the server to be up
      run: sleep 30

    - name: Test the deployment
      run: curl http://localhost:3000 | grep React

    - name : Terminate the docker Container
      run: docker stop Renti

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::818341956246:role/ECRGithubActionsRole
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag and Push docker image to Amazon ECR
      env:
        REGISTRY:  ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: renti_frontend
      run: |
        docker tag renti_frontend:v1 818341956246.dkr.ecr.us-east-1.amazonaws.com/renti_frontend:v1
        docker push 818341956246.dkr.ecr.us-east-1.amazonaws.com/renti_frontend:v1

  
